<?php

/**
 * @file
 * Implements hello_world module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_node_view_alter().
 */
function hello_world_node_view_alter(&$build, $node, $display, $view_mode, $langcode) {
  $append_types = array();
  $config = \Drupal::config('hello_world.settings');
  $types = $config->get('types');

  foreach ($types as $key => $value) {
    if ($value !== 0) {
      $append_types[] = $key;
    }
  }

  if (in_array($node->getType(), $append_types)) {
    $build['hello_world_new_content'] = array(
      '#markup' => t('Hello World!'),
    );
  }
}
